spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql
    url: jdbc:mysql://localhost:13306/test
    username: root
    password: root
